name: mix

on:
  pull_request:
  push:
    branches: [master]
  schedule:
    - cron: "42 9 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    name: test (elixir=${{ matrix.elixir }}, otp=${{ matrix.otp }})

    env:
      MIX_ENV: test

    strategy:
      matrix:
        include:
          - elixir: 1.17
            otp: 26
          - elixir: 1.19
            otp: 28
            lint: true
            dialyzer: true

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Restore deps cache
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: test-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-${{ github.head_ref || github.ref }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            test-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-${{ github.head_ref || github.ref }}-
            test-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-refs/heads/master-

      - run: mix deps.get --only $MIX_ENV
        if: ${{ !matrix.lint }}

      - run: mix deps.get --check-locked
        if: ${{ matrix.lint }}

      - run: mix deps.unlock --check-unused
        if: ${{ matrix.lint }}

      - run: mix compile --warnings-as-errors

      - run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - run: mix test

      - name: Restore PLTs cache
        uses: actions/cache@v4
        with:
          path: plts
          key: plts-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-${{ github.head_ref || github.ref }}
          restore-keys: |
            plts-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-refs/heads/main

      - run: mix dialyzer --format github

  # bench:
  #   runs-on: ubuntu-latest

  #   env:
  #     MIX_ENV: bench

  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: erlef/setup-beam@v1
  #       with:
  #         elixir-version: 1.19
  #         otp-version: 28

  #     - uses: actions/cache@v4
  #       with:
  #         path: |
  #           deps
  #           _build
  #         key: bench-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-${{ github.head_ref || github.ref }}-${{ hashFiles('**/mix.lock') }}
  #         restore-keys: |
  #           bench-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-${{ github.head_ref || github.ref }}-
  #           bench-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-refs/heads/master-

  #     - run: mix deps.get --only $MIX_ENV
  #     - run: mix compile --warnings-as-errors
  #     - run: mix run bench/bind_all.exs
  #     - run: mix run bench/insert_all.exs
  #     - run: mix run bench/fetch_all.exs
